// AUTO-GENERATED by scripts/generate-registry.mjs — do not edit manually.
import type { PluginManifest } from '@cms/core';

export const pluginManifests: Record<string, PluginManifest> = {
  "hello-world": {
    "id": "hello-world",
    "name": "Hello World",
    "version": "1.0.0",
    "description": "Plugin contoh: mendemonstrasikan hook action, filter konten, dan halaman admin sendiri.",
    "author": "CMS Cloud",
    "entry": "src/index.ts",
    "requires": ">=0.1.0"
  },
};

export const pluginEntries: Record<string, () => Promise<{ default: import('@cms/core').PluginRegistration }>> = {
  "hello-world": () => import("@cms-plugins/hello-world"),
};
