import type { Hooks } from './hooks.ts';
import type { PluginManifest } from './types.ts';
import { satisfiesRequires, CORE_VERSION } from './version.ts';

export type { Hooks };

/** Key-value store plugins can persist to (backed by D1 options). */
export interface PluginOptionsStore {
  get(name: string): Promise<string | undefined>;
  set(name: string, value: string): Promise<void>;
  delete(name: string): Promise<void>;
}

/** Server-rendered admin page contributed by a plugin (WordPress-like). */
export interface AdminPageDef {
  slug: string;
  title: string;
  /** Renders the page body. `request` carries query params / headers. */
  render(args: { request: Request; currentUser: { id: string; username: string; role: string } }): Promise<string>;
}

export interface PluginContext {
  id: string;
  name: string;
  version: string;
  manifest: PluginManifest;
  hooks: Hooks;
  options: PluginOptionsStore;
  /** Storage bindings (Cloudflare). Shape depends on host env. */
  storage: {
    d1: unknown;
    r2: unknown;
    kv: unknown;
  };
  admin: {
    registerPage(definition: AdminPageDef): void;
    pages: AdminPageDef[];
  };
  log: {
    info(message: string): void;
    error(message: string, error?: unknown): void;
  };
}

export type PluginRegistration = (context: PluginContext) => void | {
  activate?: () => void | Promise<void>;
  deactivate?: () => void | Promise<void>;
};

export interface LoadedPlugin {
  manifest: PluginManifest;
  context: PluginContext;
  activate: () => Promise<void>;
  deactivate: () => Promise<void>;
}

export interface HostDeps {
  hooks: Hooks;
  options: PluginOptionsStore;
  storage: PluginContext['storage'];
  log?: (message: string) => void;
}

export type PluginEntryResolver = Record<string, () => Promise<{ default: PluginRegistration }>>;

/**
 * Loads and registers the given plugin entry. WordPress-like:
 * runs the module's default export (`register(context)`) against a
 * PluginContext. Use `requireVersion` to enforce host compatibility.
 */
export async function loadPlugin(
  entry: { default: PluginRegistration },
  manifest: PluginManifest,
  deps: HostDeps,
): Promise<LoadedPlugin> {
  if (!satisfiesRequires(manifest.requires)) {
    throw new Error(`Plugin "${manifest.id}" requires core ${manifest.requires}, but core is ${CORE_VERSION}`);
  }

  const context: PluginContext = {
    id: manifest.id,
    name: manifest.name,
    version: manifest.version,
    manifest,
    hooks: deps.hooks,
    options: deps.options,
    storage: deps.storage,
    admin: {
      pages: [],
      registerPage(definition) {
        this.pages.push(definition);
      },
    },
    log: {
      info: (message) => deps.log?.(`[plugin:${manifest.id}] ${message}`),
      error: (message, error) => deps.log?.(`[plugin:${manifest.id}] ERROR ${message} ${error instanceof Error ? error.message : String(error)}`),
    },
  };

  const lifecycle = ((await entry.default(context)) ?? {}) as Record<string, unknown>;
  return {
    manifest,
    context,
    activate: async () => {
      const fn = lifecycle.activate;
      if (typeof fn === 'function') await (fn as () => void | Promise<void>)();
    },
    deactivate: async () => {
      const fn = lifecycle.deactivate;
      if (typeof fn === 'function') await (fn as () => void | Promise<void>)();
    },
  };
}

/**
 * Bootstraps all active plugins. `activeIds` is the list of plugin ids stored
 * in options under `active_plugins` (JSON). Entries/manifests come from the
 * build-time registry (generated by scripts/generate-registry.mjs).
 */
export async function bootstrapPlugins(
  entries: PluginEntryResolver,
  manifests: Record<string, PluginManifest>,
  activeIds: string[],
  deps: HostDeps,
): Promise<Map<string, LoadedPlugin>> {
  const loaded = new Map<string, LoadedPlugin>();
  for (const id of activeIds) {
    const resolve = entries[id];
    const manifest = manifests[id];
    if (!resolve || !manifest) continue;
    try {
      const entry = await resolve();
      const loadedPlugin = await loadPlugin(entry, manifest, deps);
      await loadedPlugin.activate();
      loaded.set(id, loadedPlugin);
    } catch (error) {
      deps.log?.(`[hooks] failed to load plugin "${id}": ${error instanceof Error ? error.message : String(error)}`);
    }
  }
  return loaded;
}